
services:
  app:
    build: .
    container_name: youthful_cannon
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "True"
      DB_HOST: ${DB_HOST_NAME}
      DB_HOST_NAME: ${DB_HOST_NAME}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT_NUMBER}

    volumes:
      - static_data:/app/staticfiles

    healthcheck:
      # will need to add an actual endpoint here for the healthcheck of the container running
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

volumes:
  static_data: